"""add campaigns table, move lore_world from conversations to campaigns

Revision ID: 56bc818fe963
Revises: 67858868123c
Create Date: 2026-04-08 14:44:18.896093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56bc818fe963'
down_revision: Union[str, Sequence[str], None] = '67858868123c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lore_world', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('conversations', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_campaign_id'), 'conversations', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'campaigns', ['campaign_id'], ['id'])
    op.drop_column('conversations', 'lore_world')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('lore_world', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_campaign_id'), table_name='conversations')
    op.drop_column('conversations', 'campaign_id')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
