"""make campaign_id non-nullable on conversations

Revision ID: 56e360eaad6f
Revises: 56bc818fe963
Create Date: 2026-04-08 14:57:14.943699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e360eaad6f'
down_revision: Union[str, Sequence[str], None] = '56bc818fe963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
