"""unique constraint

Revision ID: 6e3fadd66a9c
Revises: 38d0e4596967
Create Date: 2026-02-18 10:48:48.254027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3fadd66a9c'
down_revision: Union[str, Sequence[str], None] = '38d0e4596967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=True)
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    # ### end Alembic commands ###
