"""add worlds and lore_entries tables, conversation world_id FK

Revision ID: ca87f8dc93da
Revises: 7147ab12134a
Create Date: 2026-04-07 16:09:42.915340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca87f8dc93da'
down_revision: Union[str, Sequence[str], None] = '7147ab12134a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_name'), 'worlds', ['name'], unique=True)
    op.create_table('lore_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lore_entries_world_id'), 'lore_entries', ['world_id'], unique=False)
    op.add_column('conversations', sa.Column('world_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_conversations_world_id'), 'conversations', ['world_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'worlds', ['world_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_world_id'), table_name='conversations')
    op.drop_column('conversations', 'world_id')
    op.drop_index(op.f('ix_lore_entries_world_id'), table_name='lore_entries')
    op.drop_table('lore_entries')
    op.drop_index(op.f('ix_worlds_name'), table_name='worlds')
    op.drop_table('worlds')
    # ### end Alembic commands ###
