"""add ingestion_status to lore_entries

Revision ID: cb887e709ca7
Revises: ca87f8dc93da
Create Date: 2026-04-07 17:24:41.724123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb887e709ca7'
down_revision: Union[str, Sequence[str], None] = 'ca87f8dc93da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lore_entries', sa.Column('ingestion_status', sa.String(), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lore_entries', 'ingestion_status')
    # ### end Alembic commands ###
