"""background and location maintained in convo object

Revision ID: cfe686294f54
Revises: 97f2fb500fc9
Create Date: 2026-02-24 18:09:44.785038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe686294f54'
down_revision: Union[str, Sequence[str], None] = '97f2fb500fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('location', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('story_background', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('lore_world', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'lore_world')
    op.drop_column('conversations', 'story_background')
    op.drop_column('conversations', 'location')
    # ### end Alembic commands ###
